version: '3'
services:
  blog.work.net:
      build: ./
      container_name: my_blog
      restart: always
      ports:
        - "4000:4000"
      volumes:
        - ./_config.yml:/var/blog/_config.yml
        - ./scaffolds:/var/blog/scaffolds
        - ./source:/var/blog/source
        - ./themes:/var/blog/themes