version: '3.5'
services:
  blog:
      image: tomhjx/hexo:5.4.0-next-8.7.0-centos-7-beta.2
      command: ["hexo", "server", "--debug"]
      restart: always
      ports:
        - "4000:4000"
      volumes:
        - ./uploads:/var/www/blog/themes/next/source/uploads
        - ./_config.next.yml:/var/www/blog/_config.next.yml
        - ./_config.yml:/var/www/blog/_config.yml
        - ./scaffolds:/var/www/blog/scaffolds
        - ./source:/var/www/blog/source
        - /Users/tom/.ssh/id_rsa:/root/.ssh/id_rsa
        - /Users/tom/.gitconfig:/root/.gitconfig